cluster:
  networking:
    apiServer:
      address: "127.0.0.1"
      port: 9669
    podSubnet: "10.244.0.0/16"
    serviceSubnet: "10.96.0.0/16"
    disableDefaultCNI: true
    kubeProxyMode: "iptables"
  # NOT ENABLE, DEFAULT NEED AT LEAST 1 CONTROL PLANE (UPDATE LATER)
  # role: "worker"
  image: "kindest/node:v1.28.9"
