---
# Playbook for provision Kubernete node
- name: Playbook of Kubernetes Node with KIND
  vars:
    cluster_name: "{{ host_name }}"
    user: "vagrant"
  # To fix lint issues: when you not set host_name, use default func of jinja2 to handle
  # https://stackoverflow.com/questions/35105615/use-a-default-if-a-variable-is-not-defined
  hosts: "{{ host_name | default('sample-k8s-master') }}"
  tasks:
    - name: Install common libraries,kind and dependencies for your host
      tags: install_common
      # Help to do inline script and multiple line
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: |-
        sudo apt update
        sudo apt install -y apt-transport-https ca-certificates curl gpg wget
        wget -q https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64 -O ./kind
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
      changed_when: false
      args:
        executable: /bin/bash
      register: shell_output

    - name: Log the results of install common
      # Use `debug` feature to log your progress when perform the script, such as output or error
      # to your ansible shell. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
      tags: install_common
      ansible.builtin.debug:
        msg: "{{ shell_output.stdout_lines }}"

    - name: Access master var_files
      tags: setup_kind
      # Use `include_vars` to handling to task to import
      # host_vars base on conditional
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html
      ansible.builtin.include_vars:
        file: "./inventories/host_vars/master.yaml"
      # `when` conditional inside the ansible which help handle configuration,
      # and give the flexible to dynamic tasks on ansible
      # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html
      when: cluster_name is search("master")

    - name: Access worker var_files
      tags: setup_kind
      ansible.builtin.include_vars:
        file: "./inventories/host_vars/worker.yaml"
      when: cluster_name is search("worker")

    - name: Bring up Kind cluster
      tags: setup_kind
      block:
        - name: Create kind directory for host
          # Use `command` feature, if you want to execute command in your remote host
          # Besides, you can use `shell`, `script` or `win_shell` to do same thing but multiple line or run script-file optional
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
          ansible.builtin.command:
            cmd: "mkdir -p ~/.kind"
          # Ansible lets you define when a particular task has “changed” a remote node using the changed_when conditional
          # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_error_handling.html#defining-changed
          changed_when: false

        - name: Mount the kind-config template to the host
          # Use `template` feature, to handle your situation on load template jinja2 to host
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
          ansible.builtin.template:
            src: "./templates/kind-config.yaml.j2"
            dest: "~/.kind/kind-config.yaml"
            owner: "{{ user }}"
            mode: "0644"

        - name: Bring up the cluster base on cluster
          # Same reason as `command` feature above, but can do inline script and multiple line
          # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
          ansible.builtin.shell: |-
            kindCheck="$(kind get clusters)"
            if [ $kindCheck != "" ]; then
              echo "Exist cluster already"
            else
              kind create cluster --config ~/.kind/kind-config.yaml
              echo "Create a new cluster succeed"
            fi
          register: kind_log
          changed_when: false

        - name: Log the results of Playbook K8s master node
          tags: setup_kind
          # Use `debug` feature to log your progress when perform the script, such as output or error
          # to your ansible shell. https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
          ansible.builtin.debug:
            msg: "{{ kind_log.stdout_lines }}"
