{{- $createRole := default .Values.rbac.create .Values.rbac.role.create }}
{{- if $createRole }}
{{- $roleKind := default "Role" .Values.rbac.role.kind -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleKind }}
metadata:
  name: {{ default (include "common.fullname" .) .Values.rbac.role.name }}
  {{- if ne $roleKind "ClusterRole" }}
  namespace: {{ default (include "common.namespace" .) .Values.rbac.role.namespace }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.rbac.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.rbac.role.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
