{{- $createRole := default .Values.rbac.create .Values.rbac.role.create }}
{{- if $createRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ default "Role" .Values.rbac.role.kind }}
metadata:
  name: {{ template "common.fullname" . }}
  {{- if ne (default "Role" .Values.rbac.role.kind) "ClusterRole" }}
  namespace: {{ include "common.namespace" . }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.rbac.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.rbac.role.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
