{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "ExternalName" }}
  type: ExternalName
  externalName: {{ required "service.externalName is required when service.type is ExternalName" .Values.service.externalName }}
  {{- else if and .Values.service.type (not .Values.service.headless ) }}
  type: {{ .Values.service.type }}
  {{- else }}
  clusterIP: None
  {{- end }}
  ports:
    {{- include "common.servicePorts.render" . | nindent 4 }}
  {{- if ne .Values.service.type "ExternalName" }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  {{- end }}
  
{{- end }}