name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Xeus Nguyen"
          git config user.email "xeusnguyen@gmail.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: true
          charts_dir: kubernetes/charts
          pages_branch: main
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"