apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/Xeus-Territory/kubewekend.git
  sourceNamespaces:
    - '*'
  destinations:
    # Allow apps to be installed in any namespace and any cluster.
    - server: '*'
      namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'